version: "3.4"

services:
  saleor:
    image: saleor
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    command: sleep infinity
    env_file:
      - common.env
      - backend.env
    volumes:
      - ..:/app
    # 'depends_on' is removed as db and redis are now external

  dashboard:
    image: ghcr.io/saleor/saleor-dashboard:3.20.5
    restart: unless-stopped
    ports:
      - 9000:80

  mailpit:
    image: axllent/mailpit
    ports:
      - 1025:1025 # SMTP Server
      - 8025:8025 # Mailpit UI
    restart: unless-stopped

# Volumes for the removed db and redis services are also removed.
